services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=mail@freundt.dev"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  portfolio:
    image: ghcr.io/nicofreundt/portfolio/portfolio:latest
    labels:
      - "traefik.enable=true"

      # Handles requests for www.freundt.dev
      - "traefik.http.routers.portfolio.rule=Host(`www.freundt.dev`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      
      # Handles redirect from freundt.dev to www.freundt.dev
      - "traefik.http.routers.redirect-freundt-dev.rule=Host(`freundt.dev`)"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.regex=^https://freundt.dev(.*)"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.replacement=https://www.freundt.dev$${1}"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true"
      - "traefik.http.routers.redirect-freundt-dev.middlewares=redirect-to-www"
      - "traefik.http.routers.redirect-freundt-dev.entrypoints=websecure"
      - "traefik.http.routers.redirect-freundt-dev.tls.certresolver=myresolver"
      
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      mode: replicated
      replicas: 3
    restart: always
volumes:
  letsencrypt:
