name: Build and Push Docker image

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build --build-arg TOKEN=${{ secrets.VITE_API_TOKEN }} -t ghcr.io/${{ github.repository }}/portfolio:latest .
          docker push ghcr.io/${{ github.repository }}/portfolio:latest
